// Code generated by "stringer -type=Tag"; DO NOT EDIT.

package bert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Version-131]
	_ = x[CompressedZlib-80]
	_ = x[AtomCacheRef-82]
	_ = x[SmallIntegerExt-97]
	_ = x[IntegerExt-98]
	_ = x[FloatExt-99]
	_ = x[PortExt-102]
	_ = x[NewPortExt-89]
	_ = x[V4PortExt-120]
	_ = x[PidExt-103]
	_ = x[NewPidExt-88]
	_ = x[SmallTupleExt-104]
	_ = x[LargeTupleExt-105]
	_ = x[MapExt-116]
	_ = x[NilExt-106]
	_ = x[StringExt-107]
	_ = x[ListExt-108]
	_ = x[BinaryExt-109]
	_ = x[SmallBigExt-110]
	_ = x[LargeBigExt-111]
	_ = x[ReferenceExt-101]
	_ = x[NewReferenceExt-114]
	_ = x[NewerReferenceExt-90]
	_ = x[FunExt-117]
	_ = x[NewFunExt-112]
	_ = x[ExportExt-113]
	_ = x[BitBinaryExt-77]
	_ = x[NewFloatExt-70]
	_ = x[AtomUtf8Ext-118]
	_ = x[SmallAtomUtf8Ext-119]
	_ = x[AtomExt-100]
	_ = x[SmallAtomExt-115]
	_ = x[LocalExt-121]
}

const (
	_Tag_name_0 = "NewFloatExt"
	_Tag_name_1 = "BitBinaryExt"
	_Tag_name_2 = "CompressedZlib"
	_Tag_name_3 = "AtomCacheRef"
	_Tag_name_4 = "NewPidExtNewPortExtNewerReferenceExt"
	_Tag_name_5 = "SmallIntegerExtIntegerExtFloatExtAtomExtReferenceExtPortExtPidExtSmallTupleExtLargeTupleExtNilExtStringExtListExtBinaryExtSmallBigExtLargeBigExtNewFunExtExportExtNewReferenceExtSmallAtomExtMapExtFunExtAtomUtf8ExtSmallAtomUtf8ExtV4PortExtLocalExt"
	_Tag_name_6 = "Version"
)

var (
	_Tag_index_4 = [...]uint8{0, 9, 19, 36}
	_Tag_index_5 = [...]uint8{0, 15, 25, 33, 40, 52, 59, 65, 78, 91, 97, 106, 113, 122, 133, 144, 153, 162, 177, 189, 195, 201, 212, 228, 237, 245}
)

func (i Tag) String() string {
	switch {
	case i == 70:
		return _Tag_name_0
	case i == 77:
		return _Tag_name_1
	case i == 80:
		return _Tag_name_2
	case i == 82:
		return _Tag_name_3
	case 88 <= i && i <= 90:
		i -= 88
		return _Tag_name_4[_Tag_index_4[i]:_Tag_index_4[i+1]]
	case 97 <= i && i <= 121:
		i -= 97
		return _Tag_name_5[_Tag_index_5[i]:_Tag_index_5[i+1]]
	case i == 131:
		return _Tag_name_6
	default:
		return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
